export const milanPoem = [
    "Milan, a story in every stone, centuries old.",
    "A fiery furnace cannot dim , the effervescence of my maiden",
    "She is the torrent and the vessel, the brushstroke and the canvas",
    "Her body is an inscription older than hieroglyphs",
    "Her voice is full of poise itself , walking and speaking",
    "When she is moved, even Poseidon falters, awed by the flood she commands",
    "Swallows curse her for the way she glides",
    "She is mercurial - untouchable, silver, slipping free",
    "At her name , kings quiver and unravel",
    "Clawing at the base of her mountain hungry to climb higher to climb higher",
    "And I - ",
    "a prophet bound to her shadow",
    "forelling the ruin of those who dare peek under her wings",
  ];